config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :doctors
  resources :patients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  SPECIALITY = ["cardiologue", "pediatre", "neurologue", "endocrinologue", "ophtamologue", "ORL"]
  has_one :user, as: :userable, dependent: :destroy
  accepts_nested_attributes_for :user

  # Recherche du docteur
  # include PgSearch::Model
  # pg_search_scope :global_search,
  #   against: [:speciality],
  #   associated_against: { user: %i[lastname]},
  #   using: { tsearch: {prefix: true} }

  # Validation
  validates_presence_of :speciality, inclusion: {in: SPECIALITY}
end

app/models/patient.rb
class Patient < ApplicationRecord
  GENDER = ['masculin', 'féminin']

  # Association
  has_one :user, as: :userable, dependent: :destroy
  accepts_nested_attributes_for :user

  # Validation
  validates :gender, inclusion: {in: GENDER}
  validates_presence_of :birth_date
  validates_presence_of :address
  validates_presence_of :zipcode
  validates_presence_of :city
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Association Polymorphique
  belongs_to :userable, polymorphic: true

  # Validation
  validates_presence_of :firstname
  validates :lastname, presence: true, uniqueness: {scope: :firstname}
  validates :phone_number, presence: true, format: { with:  /(?:((?:\+|00)33)|0)\s*[1-9](?:[\s.-]*\d{2}){4}/}

  #Photo
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number])
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :authenticate_user!, :authenticate_doctor, except: %i[index new create show]
  before_action :new_registration, only: %i[new create]
  before_action :set_doctor, only: %i[show edit update]

  def index
    @doctors = Doctor.all
    unless params[:query].nil?
      sql_subquery = <<~SQL
      doctors.speciality ILIKE :query
      OR users.lastname ILIKE :query
      SQL
      @doctors = @doctors.joins(:user).where(sql_subquery, query: "%#{params[:query]}%")
    end
  end

  def show;end

  def new
    @doctor = Doctor.new
    @doctor.build_user
  end

  def create
    @doctor = Doctor.new(doctor_params)

    if @doctor.save!
      redirect_to new_user_session_path, notice: 'Votre compte a bien été créé.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @doctor.update(doctor_params)
      @doctor.user = @doctor.user || User.new(params[:user])
      redirect_to @doctor, notice: 'Votre compte a bien été mis à jour.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(
      :speciality,
      user_attributes: [:firstname, :lastname, :phone_number, :password, :email]
      )
  end

  def authenticate_doctor
    redirect_to new_user_session_path unless current_user.userable_type == "Doctor"
  end

  def new_registration
    redirect_to doctors_path if user_signed_in?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!, :authenticate_patient, except: %i[index new create show]
  before_action :new_registration, only: %i[new create]
  before_action :set_patient, only: %i[show edit update]

  # GET patients/
  def index
    @patients = Patient.all
  end

  # GET patient/:id
  def show; end

  # GET patients/new
  def new
    @patient = Patient.new
    @patient.build_user
  end

  # POST patients/new
  def create
    @patient = Patient.new(patient_params)

    if @patient.save!
      redirect_to @patient, notice: 'Votre compte a bien été créé.'
    else
      render :new, status: :unprocessable_entity
    end
  end


  def edit; end

  def update
    if @patient.update(patient_params)
      @patient.user = @patient.user || User.new(params[:user])
      redirect_to @patient, notice: 'Votre compte a bien été mis à jour.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(
      :gender, :birth_date, :address, :zipcode, :city,
      user_attributes: [:firstname, :lastname, :phone_number, :password, :email]
      )
  end

  def authenticate_patient
    redirect_to new_user_session_path unless current_user.userable_type == "Patient"
  end

  def new_registration
    redirect_to patients_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/doctors/index.html.erb
<div class="bg-white py-24 sm:py-32">
  <div class="mx-auto max-w-7xl px-6 lg:px-8">
    <div class="mx-auto max-w-2xl lg:mx-0">
      <h2 class="text-3xl font-bold tracking-tight emerald sm:text-4xl">From the blog</h2>
      <p class="mt-2 text-lg leading-8 emerald">Learn how to grow your business with our expert advice.</p>
    </div>
    <div class="row justify-content-center">
      <div class="col-sm-8 my-3">
        <%= form_with url: doctors_path, method: :get, class: "flex flex-1 pt-2 relative mx-auto text-gray-600" do %>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control border-2 bg-white h-10 px-3 pr-16 rounded-lg text-sm focus:outline-none",
                placeholder: "Choisissez votre docteur"
          %>
          <%= button_tag( class: "btn btn-clr") do %>
            <svg class="h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg"
              xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px"
              viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve"
              width="512px" height="512px">
              <path
                d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z" />
            </svg>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="py-8 bbh">
      <div class="my-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <ul role="list" class="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 pl-0">
          <% @doctors.each do |doctor| %>
            <li class="col-span-1 flex flex-col rounded-lg bg-white box-shadow-clr text-center">
              <div class="flex flex-1 flex-col p-8">
                <%= cl_image_tag doctor.user.photo.key , alt:"", class:"mx-auto h-32 w-32 shrink-0 rounded-full"%>
                <h3 class="mt-7 text-sm font-medium text-gray-900"> Dr <%= doctor.user.lastname %></h3>
                <dl>
                  <dt></dt>
                  <dd class="font-medium text-sm text-gray-500"><%= doctor.speciality %></dd>
                  <dt></dt>
                  <dd class="mt-3"><span class="inline-flex shrink-0 items-center rounded-full bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-opacity-20 ring-green-600">Admin</span></dd>
                </dl>
              </div>
              <div>
                <div class="jf flex acb acg">
                  <div class="flex w-0 flex-1">
                    <a id="icone_email" href="mailto:<%= doctor.user.email %>" class="relative io inline-flex w-0 flex-1 items-center justify-center gap-x-3 rounded-bl-lg border-clr border-transparent py-3 text-sm font-semibold axu">
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" class="h-5 w-5 text-gray-400">
                        <path d="M3 4a2 2 0 00-2 2v1.161l8.441 4.221a1.25 1.25 0 001.118 0L19 7.162V6a2 2 0 00-2-2H3z"></path>
                        <path d="M19 8.839l-7.77 3.885a2.75 2.75 0 01-2.46 0L1 8.839V14a2 2 0 002 2h14a2 2 0 002-2V8.839z"></path>
                      </svg>
                      Email
                    </a>
                  </div>
                  <div class="ia flex w-0 flex-1">
                    <a id="icone_tel" href="tel:+1-202-555-0143" class="relative inline-flex w-0 flex-1 items-center justify-center gap-x-3 rounded-br-lg border-clr border-transparent py-3 text-sm font-semibold axu">
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" class="h-5 w-5 text-gray-400">
                        <path fill-rule="evenodd" d="M2 3.5A1.5 1.5 0 013.5 2h1.148a1.5 1.5 0 011.465 1.175l.716 3.223a1.5 1.5 0 01-1.052 1.767l-.933.267c-.41.117-.643.555-.48.95a11.542 11.542 0 006.254 6.254c.395.163.833-.07.95-.48l.267-.933a1.5 1.5 0 011.767-1.052l3.223.716A1.5 1.5 0 0118 15.352V16.5a1.5 1.5 0 01-1.5 1.5H15c-1.149 0-2.263-.15-3.326-.43A13.022 13.022 0 012.43 8.326 13.019 13.019 0 012 5V3.5z" clip-rule="evenodd"></path>
                      </svg>
                      Call
                    </a>
                  </div>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  </div>
</div>

app/views/doctors/new.html.erb
<div class=bg-white>
  <div class='container p-3'>
    <div class='row justify-content-center'>
      <div class= "border rounded col-12 col-sm-10 col-md-8 col-lg-5 clr-dr">
        <%= simple_form_for (@doctor) do |f| %> <h2 class="text-center m-3">Inscription d'un docteur</h2>
          <%= f.error_notification %>

          <div class="form-inputs">

            <%= f.simple_fields_for :user_attributes do |u| %>
              <%= u.error_notification %>

              <div class="row mb-3">
                <div class="col-6">
                  <%= u.label "Prénom" %>
                  <%= u.input :firstname,
                              label: false,
                              required: true,
                              autofocus: true,
                              autocomplete: "given-name",
                              class:"form-control" %>
                </div>
                <div class="col-6">
                  <%= u.label "Nom" %>
                  <%= u.input :lastname,
                              label: false,
                              required: true,
                              autofocus: true,
                              autocomplete: "family-name",
                              class:"form-control" %>
                </div>
              </div>
              <div class="row mb-2">
                <div class="col-4">
                  <%= u.label "Email" %>
                </div>
                <div class="col-8">
                  <%= u.input :email,
                              label: false,
                              required: true,
                              autofocus: true,
                              autocomplete: "email", class:"form-control" %>
                </div>
              </div>
              <div class="row mb-2">
                <div class="col-4">
                  <%= u.label "Mot de passe" %>
                </div>
                <div class="col-8">
                  <%= u.input :password,
                                    type: "password",
                                    label: false,
                                    hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                                    autocomplete: "new-password", class:"form-control" %>
                </div>
              </div>
              <div class="row mb-2">
                <div class="col-4">
                  <%= u.label "Confirmation du Mot de passe" %>
                </div>
                <div class="col-8">
                  <%= u.input :password_confirmation,
                                    type: "password",
                                    label: false,
                                    autocomplete: "new-password", class:"form-control" %>
                </div>
              </div>
              <div class="row mb-2">
                <div class="col-4">
                  <%= u.label "Téléphone" %>
                </div>
                <div class="col-8">
                  <%= u.input :phone_number,
                              label: false,
                              autofocus: true,
                              class: "form-control", autocomplete: "tel-national"%>
                </div>
              </div>
  	        <% end %>

            <div class="row mb-3 border-top pt-3">
              <div class="col-4">
                <%= f.label "Spécialité" %>
                <abbr title="required">*</abbr>
              </div>
              <div class="col-8">
                <%= f.input  :speciality,
                              collection: Doctor::SPECIALITY,
                              label: false,
                              autofocus: true,
                              class:"form-control" %>
              </div>
            </div>

            <div class="row mb-3 border-top pt-3">
              <div class="col-4">
                <%= f.label "Année d'expérience" %>
                <abbr title="required">*</abbr>
              </div>
              <div class="col-8">
                <%= f.input  :experience_year,
                              label: false,
                              autofocus: true,
                              class:"form-control" %>
              </div>
            </div>
          </div>

          <div class="d-flex justify-content-around mb-2">
            <%- if request.path == new_doctor_path %>
              <%= link_to "Annuler", new_user_session_path, class: "btn btn-clr py-3 px-5" %><br />
            <% end -%>

            <div class="form-actions">
              <%= f.submit "S'inscrire", class: "btn btn-clr-dr py-3 px-5" %>
            </div>

          </div>

        <% end %>


        <!--%= render "devise/shared/links" %-->
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CliniqueV2</title>
    <%= favicon_link_tag 'logo.png' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
    />

    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>

  </head>

  <body>
    <%= render "shared/flashes" %>
    <main class="flex-grow" data-controller="scroll-on-click">
      <%= render "shared/navbar" %>
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<!-- slider section -->
<section data-controller="slide" class="swiper">
  <!-- Additional required wrapper -->
  <div class="swiper-wrapper">
    <!-- Slides -->
    <div class="swiper-slide px-2 mx-2">
      <div class="detail-box">
        <div class="play_btn">
          <button>
            <i class="fa fa-play" aria-hidden="true"></i>
          </button>
        </div>
        <h1>
          Mico <br>
          <span>
            Hospital
          </span>
        </h1>
        <p>
          When looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to
        </p>
        <a href="">
          Contact Us
        </a>
      </div>
    </div>
    <div class="swiper-slide px-2 mx-2">
      <div class="img-box">
        <%= image_tag "slider-img.jpg", alt:"", width:400 %>
      </div>
    </div>
    <div class="swiper-slide px-2 mx-2">
      <div class="detail-box">
        <div class="play_btn">
          <button>
            <i class="fa fa-play" aria-hidden="true"></i>
          </button>
        </div>
        <h1>
          Mico <br>
          <span>
            Hospital
          </span>
        </h1>
        <p>
          When looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to
        </p>
        <a href="">
          Contact Us
        </a>
      </div>
    </div>
    <div class="swiper-slide px-2 mx-2">
      <div class="img-box">
        <%= image_tag "contact-img.jpg", alt:"", width:400 %>
      </div>
    </div>
    <div class="swiper-slide px-2 mx-2">
      <div class="detail-box">
        <div class="play_btn">
          <button>
            <i class="fa fa-play" aria-hidden="true"></i>
          </button>
        </div>
        <h1>
          Mico <br>
          <span>
            Hospital
          </span>
        </h1>
        <p>
          When looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to
        </p>
        <a href="">
          Contact Us
        </a>
      </div>
    </div>
    <div class="swiper-slide px-2 mx-2">
      <div class="img-box">
        <%= image_tag "about-img.jpg", alt:"", width:400 %>
      </div>
    </div>
  </div>
  <!-- If we need navigation buttons -->
  <div class="swiper-button-prev"></div>
  <div class="swiper-button-next"></div>

  <!-- If we need pagination -->
  <div class="swiper-pagination"></div>
</section>
<!-- end slider section -->


<!-- about section -->

<section class="about_section layout_padding">
  <div class="container">
    <div class="row" data-scroll-on-click-target="about">
      <div class="col-md-6 ">
        <div class="img-box">
          <%= image_tag "about-img.jpg", alt:""%>
        </div>
      </div>
      <div class="col-md-6">
        <div class="detail-box">
          <div class="heading_container">
            <h2>
              About <span>Hospital</span>
            </h2>
          </div>
          <p>
            has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors
          </p>
          <a href="">
            Read More
          </a>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- end about section -->


<!-- contact section -->
<section class="contact_section layout_padding-bottom">
  <div class="container">
    <div class="heading_container" data-scroll-on-click-target="contact">
      <h2>
        Envoyez un message
      </h2>
    </div>
    <div class="row">
      <div class="col-md-7">
        <div class="form_container">
          <% if user_signed_in? && current_user.userable_type == "Patient" %>
            <%= simple_form_for(current_user) do |f| %>
              <div class="row">
                <div class="col"><%= f.input :firstname, value: current_user.firstname, input_html: {class:"form-control", autocomplete: "given-name"} %></div>
                <div class="col"><%= f.input :lastname, value: current_user.lastname, input_html: {class:"form-control", autocomplete: "family-name"} %></div>
              </div>
              <div><%= f.input :email, label: "Email", value: current_user.email, input_html: {class:"form-control", autocomplete: "email"} %></div>
              <div><%= f.input :phone_number, label: "Téléphone", value: current_user.phone_number, input_html: {class:"form-control", autocomplete: "tel-national"} %></div>
              <div><%= f.input :lastname, label: "Message", value: "Message", input_html: {class:"message-box clr", autocomplete: "tel-national"} %></div>

              <div class="btn_box">
                <div class="form-actions">
                  <%= f.button :submit, "Envoyer"%>
                </div>
              </div>
            <% end %>
          <% else %>
          <form action="">
            <div class="row">
              <div class="col">
                <input type="name" placeholder="Prénom" class="form-control" autocomplete="given-name" />
              </div>
              <div class="col">
                <input type="name" placeholder="Nom" class="form-control" autocomplete="family-name" />
              </div>
            </div>

            <div>
              <input type="email" placeholder="Email" class="form-control" autocomplete="email" />
            </div>
            <div>
              <input type="phone" placeholder="Téléphone" class="form-control" autocomplete="tel-national" />
            </div>
            <div>
              <input type="text" placeholder="Message" class="message-box clr" class="form-control" />
            </div>
            <div class="btn_box">
              <button>
                Envoyer
              </button>
            </div>
          </form>
          <% end %>
        </div>
      </div>
      <div class="col-md-5">
        <div class="img-box">
          <%= image_tag "contact-img.jpg", alt: ""%>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- end contact section -->


<!-- treatment section -->

<section data-scroll-on-click-target="treatment" class="treatment_section layout_padding">
  <div class="side_img">
    <%= image_tag "treatment-side-img.jpg", alt:"" %>
  </div>
  <div class="container">
    <div class="heading_container heading_center">
      <h2>
        Hospital <span>Treatment</span>
      </h2>
    </div>
    <div class="row">
      <div class="col-md-6 col-lg-3">
        <div class="box ">
          <div class="img-box">
            <%= image_tag "t1.png", alt:"" %>
          </div>
          <div class="detail-box">
            <h4>
              Nephrologist Care
            </h4>
            <p>
              alteration in some form, by injected humour, or randomised words which don't look even slightly e sure there isn't anything
            </p>
            <a href="">
              Read More
            </a>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-3">
        <div class="box ">
          <div class="img-box">
            <%= image_tag "t2.png", alt:"" %>
          </div>
          <div class="detail-box">
            <h4>
              Eye Care
            </h4>
            <p>
              alteration in some form, by injected humour, or randomised words which don't look even slightly e sure there isn't anything
            </p>
            <a href="">
              Read More
            </a>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-3">
        <div class="box ">
          <div class="img-box">
            <% image_tag "t3.png", alt:"" %>
          </div>
          <div class="detail-box">
            <h4>
              Pediatrician Clinic
            </h4>
            <p>
              alteration in some form, by injected humour, or randomised words which don't look even slightly e sure there isn't anything
            </p>
            <a href="">
              Read More
            </a>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-3">
        <div class="box ">
          <div class="img-box">
            <%= image_tag "t4.png", alt:"" %>
          </div>
          <div class="detail-box">
            <h4>
              Parental Care
            </h4>
            <p>
              alteration in some form, by injected humour, or randomised words which don't look even slightly e sure there isn't anything
            </p>
            <a href="">
              Read More
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- end treatment section -->

app/views/patients/new.html.erb
<div class=bg-white>
  <div class='container p-3'>
    <div class='row justify-content-center'>
      <div class= "border rounded col-12 col-sm-10 col-md-8 col-lg-5 clr-patient">
        <%= form_for @patient do |f| %> <h2 class="text-center m-3">Inscription du patient</h2>
          <% if @patient.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

              <ul>
              <% @patient.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-inputs">

            <%= f.fields_for :user_attributes, @patient.user || User.new do |u| %>
              <div class="row mb-3">
                <div class="col-6">
                  <%= u.label "Prénom" %>
                  <%= u.text_field :firstname,
                              required: true,
                              autofocus: true,
                              autocomplete: "given-name",
                              class:"form-control" %>
                </div>
                <div class="col-6">
                  <%= u.label "Nom" %>
                  <%= u.text_field :lastname,
                              required: true,
                              autofocus: true,
                              autocomplete: "family-name",
                              class:"form-control" %>
                </div>
              </div>
              <div class="row mb-2">
                <div class="col-4">
                  <%= u.label "Email" %>
                  <abbr title="required">*</abbr>
                </div>
                <div class="col-8">
                  <%= u.text_field  :email,
                                    label: false,
                                    required: true,
                                    autofocus: true,
                                    autocomplete: "email", class:"form-control" %>
                </div>
              </div>
              <div class="row mb-2">
                <div class="col-4">
                  <%= u.label "Mot de passe" %>
                  <abbr title="required">*</abbr>
                </div>
                <div class="col-8">
                  <%= u.text_field  :password,
                                    type: "password",
                                    label: false,
                                    hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                                    autocomplete: "new-password", class:"form-control" %>
                </div>
              </div>
              <div class="row mb-2">
                <div class="col-4">
                  <%= u.label "Confirmation du Mot de passe" %>
                  <abbr title="required">*</abbr>
                </div>
                <div class="col-8">
                  <%= u.text_field  :password_confirmation,
                                    type: "password",
                                    label: false,
                                    autocomplete: "new-password", class:"form-control" %>
                </div>
              </div>
              <div class="row mb-2">
                <div class="col-4">
                  <%= u.label "Téléphone" %>
                  <abbr title="required">*</abbr>
                </div>
                <div class="col-8">
                  <%= u.text_field :phone_number,
                              label: false,
                              autofocus: true,
                              class: "form-control", autocomplete: "tel-national"%>
                </div>
              </div>
  	        <% end %>

            <div class="row mb-3">
              <div class="col-4">
                <%= f.label "Sexe" %>
                <abbr title="required">*</abbr>
              </div>
              <div class="col-8">
                <%= f.select :gender, Patient::GENDER,
                                  class: "form-control",
                                  label: false %>
              </div>
            </div>

            <div class="row mb-3">
              <div class="col-4">
                <%= f.label "Date de naissance" %>
                <abbr title="required">*</abbr>
              </div>
              <div class="col-8">
                <%= f.text_field  :birth_date,
                                  label: false,
                                  html5: true,
                                  as: :date,
                                  autofocus: true,
                                  class: "form-control" %>
              </div>
            </div>

            <div class="row mb-3">
              <div class="col-4">
                <%= f.label "Adresse" %>
                <abbr title="required">*</abbr>
              </div>
              <div class="col-8">
                <%= f.text_field :address,
                            autofocus: true,
                            autocomplete: "address-level1",
                            class:"form-control" %>
              </div>
            </div>

            <div class="row mb-3">
              <div class="col-6">
                <%= f.label "Code Postal" %>
                <%= f.text_field  :zipcode,
                                  label: false,
                                  autofocus: true,
                                  autocomplete: "postal-code",
                                  class:"form-control" %>
              </div>
              <div class="col-6">
                <%= f.label "Commune" %>
                <%= f.text_field  :city,
                                  label: false,
                                  required: true,
                                  autofocus: true,
                                  class:"form-control" %>
              </div>
            </div>

          </div>

          <div class="d-flex justify-content-around mb-2">
            <%- if request.path == new_patient_path %>
              <%= link_to "Annuler", new_user_session_path, class: "btn btn-clr py-3 px-5" %><br />
            <% end -%>

            <div class="form-actions">
              <%= f.submit "S'inscrire", class: "btn btn-clr-patient py-3 px-5" %>
            </div>

          </div>

        <% end %>


        <!--%= render "devise/shared/links" %-->
      </div>
    </div>
  </div>
</div>